//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glosa.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glosa.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found in the archive: {0}.
        /// </summary>
        internal static string ArchiveEntryMissing {
            get {
                return ResourceManager.GetString("ArchiveEntryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the file inside the archive is too large.
        /// </summary>
        internal static string ArchiveEntryTooLarge {
            get {
                return ResourceManager.GetString("ArchiveEntryTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modules: an entry has no name.
        /// </summary>
        internal static string DefineModuleUnnamed {
            get {
                return ResourceManager.GetString("DefineModuleUnnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: initializeType {1} — must be one of {2}.
        /// </summary>
        internal static string DefineUnknownInitializeType {
            get {
                return ResourceManager.GetString("DefineUnknownInitializeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is read-only.
        /// </summary>
        internal static string FileReadOnly {
            get {
                return ResourceManager.GetString("FileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is in format version {0}, newer than version {1}, which this Glosa reads.
        /// </summary>
        internal static string FormatTooNew {
            get {
                return ResourceManager.GetString("FormatTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The G36 header is too short.
        /// </summary>
        internal static string G36HeaderShort {
            get {
                return ResourceManager.GetString("G36HeaderShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scripts expand to more than {0} bytes and are cut short there.
        /// </summary>
        internal static string InitCut {
            get {
                return ResourceManager.GetString("InitCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An LZH block is empty.
        /// </summary>
        internal static string LzhBlockEmpty {
            get {
                return ResourceManager.GetString("LzhBlockEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the extracted data is corrupt (CRC).
        /// </summary>
        internal static string LzhCrcMismatch {
            get {
                return ResourceManager.GetString("LzhCrcMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LZH data is corrupt.
        /// </summary>
        internal static string LzhDataBroken {
            get {
                return ResourceManager.GetString("LzhDataBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LZH header is corrupt.
        /// </summary>
        internal static string LzhHeaderBroken {
            get {
                return ResourceManager.GetString("LzhHeaderBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LZH header is cut short.
        /// </summary>
        internal static string LzhHeaderCut {
            get {
                return ResourceManager.GetString("LzhHeaderCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An LZH code table is corrupt.
        /// </summary>
        internal static string LzhTableBroken {
            get {
                return ResourceManager.GetString("LzhTableBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: unsupported compression method ({1}).
        /// </summary>
        internal static string LzhUnknownMethod {
            get {
                return ResourceManager.GetString("LzhUnknownMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The M3U file is too large.
        /// </summary>
        internal static string M3uTooLarge {
            get {
                return ResourceManager.GetString("M3uTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not UTF-8.
        /// </summary>
        internal static string NotUtf8 {
            get {
                return ResourceManager.GetString("NotUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RCP header is too short.
        /// </summary>
        internal static string RcpHeaderShort {
            get {
                return ResourceManager.GetString("RcpHeaderShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loops expand too far.
        /// </summary>
        internal static string RcpLoopTooLarge {
            get {
                return ResourceManager.GetString("RcpLoopTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Recomposer data.
        /// </summary>
        internal static string RcpNotRecomposer {
            get {
                return ResourceManager.GetString("RcpNotRecomposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A same-measure reference points at nothing valid.
        /// </summary>
        internal static string RcpSameMeasureBroken {
            get {
                return ResourceManager.GetString("RcpSameMeasureBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same-measure references go round in a circle.
        /// </summary>
        internal static string RcpSameMeasureCycle {
            get {
                return ResourceManager.GetString("RcpSameMeasureCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be read as a rule (unreadable fields are registered as 0).
        /// </summary>
        internal static string RuleUnreadable {
            get {
                return ResourceManager.GetString("RuleUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is nested more than {0} levels deep.
        /// </summary>
        internal static string YamlTooDeep {
            get {
                return ResourceManager.GetString("YamlTooDeep", resourceCulture);
            }
        }
    }
}
