//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glosa.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glosa.App.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT License..
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post about Glosa on X.
        /// </summary>
        public static string AboutPostOnX {
            get {
                return ResourceManager.GetString("AboutPostOnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Glosa.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect.
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save {0}, so the tab was left open to keep its changes.
        ///
        ///{1}.
        /// </summary>
        public static string CannotCloseUnsaved {
            get {
                return ResourceManager.GetString("CannotCloseUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load {0}.
        ///
        ///{1}.
        /// </summary>
        public static string CannotLoadDef {
            get {
                return ResourceManager.GetString("CannotLoadDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the TMIDI definition file.
        /// </summary>
        public static string CannotLoadDefTitle {
            get {
                return ResourceManager.GetString("CannotLoadDefTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the following outputs. Playback has stopped..
        /// </summary>
        public static string CannotOpenOutputs {
            get {
                return ResourceManager.GetString("CannotOpenOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open {0}.
        ///
        ///{1}.
        /// </summary>
        public static string CannotOpenPlaylist {
            get {
                return ResourceManager.GetString("CannotOpenPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the playlist.
        /// </summary>
        public static string CannotOpenPlaylistTitle {
            get {
                return ResourceManager.GetString("CannotOpenPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open outputs.
        /// </summary>
        public static string CannotOpenTitle {
            get {
                return ResourceManager.GetString("CannotOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read {0}.
        ///
        ///{1}
        ///
        ///Fix or delete define.override.yaml, and restart Glosa..
        /// </summary>
        public static string CannotReadOverride {
            get {
                return ResourceManager.GetString("CannotReadOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the target module definitions.
        /// </summary>
        public static string CannotReadOverrideTitle {
            get {
                return ResourceManager.GetString("CannotReadOverrideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read {0}, so Glosa started with the default settings.
        ///
        ///{1}
        ///
        ///The file has been kept as {2}..
        /// </summary>
        public static string CannotReadSettings {
            get {
                return ResourceManager.GetString("CannotReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read {0}, so Glosa started with the default settings.
        ///
        ///{1}
        ///
        ///The file will be left as it is when Glosa exits..
        /// </summary>
        public static string CannotReadSettingsKept {
            get {
                return ResourceManager.GetString("CannotReadSettingsKept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the settings.
        /// </summary>
        public static string CannotReadSettingsTitle {
            get {
                return ResourceManager.GetString("CannotReadSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save {0}.
        ///
        ///{1}.
        /// </summary>
        public static string CannotSavePlaylist {
            get {
                return ResourceManager.GetString("CannotSavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the playlist.
        /// </summary>
        public static string CannotSavePlaylistTitle {
            get {
                return ResourceManager.GetString("CannotSavePlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the module initialization data. Playback has stopped..
        /// </summary>
        public static string CannotSendInit {
            get {
                return ResourceManager.GetString("CannotSendInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send to output.
        /// </summary>
        public static string CannotSendTitle {
            get {
                return ResourceManager.GetString("CannotSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string DebugCopy {
            get {
                return ResourceManager.GetString("DebugCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string DebugSelectAll {
            get {
                return ResourceManager.GetString("DebugSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultPortMapName {
            get {
                return ResourceManager.GetString("DefaultPortMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song data.
        /// </summary>
        public static string DetectionData {
            get {
                return ResourceManager.GetString("DetectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached text.
        /// </summary>
        public static string DetectionDocument {
            get {
                return ResourceManager.GetString("DetectionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string DetectionFileName {
            get {
                return ResourceManager.GetString("DetectionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named first.
        /// </summary>
        public static string DetectionFirst {
            get {
                return ResourceManager.GetString("DetectionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path.
        /// </summary>
        public static string DetectionFolderPath {
            get {
                return ResourceManager.GetString("DetectionFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named last.
        /// </summary>
        public static string DetectionLast {
            get {
                return ResourceManager.GetString("DetectionLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song title.
        /// </summary>
        public static string DetectionTitle {
            get {
                return ResourceManager.GetString("DetectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (not found).
        /// </summary>
        public static string DeviceMissing {
            get {
                return ResourceManager.GetString("DeviceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as M3U.
        /// </summary>
        public static string ExportM3u {
            get {
                return ResourceManager.GetString("ExportM3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMIDI definition files.
        /// </summary>
        public static string FileTypeDefinitions {
            get {
                return ResourceManager.GetString("FileTypeDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3U playlists.
        /// </summary>
        public static string FileTypeM3u {
            get {
                return ResourceManager.GetString("FileTypeM3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string FileTypePlaylists {
            get {
                return ResourceManager.GetString("FileTypePlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI and archive files.
        /// </summary>
        public static string FileTypeSongs {
            get {
                return ResourceManager.GetString("FileTypeSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlarge.
        /// </summary>
        public static string LcdEnlarge {
            get {
                return ResourceManager.GetString("LcdEnlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Glosa....
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder....
        /// </summary>
        public static string MenuAddFolder {
            get {
                return ResourceManager.GetString("MenuAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Songs....
        /// </summary>
        public static string MenuAddSongs {
            get {
                return ResourceManager.GetString("MenuAddSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close TMIDI Definition File.
        /// </summary>
        public static string MenuCloseDefinition {
            get {
                return ResourceManager.GetString("MenuCloseDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug....
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor....
        /// </summary>
        public static string MenuMonitor {
            get {
                return ResourceManager.GetString("MenuMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings Folder.
        /// </summary>
        public static string MenuOpenConfigFolder {
            get {
                return ResourceManager.GetString("MenuOpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TMIDI Definition File....
        /// </summary>
        public static string MenuOpenDefinition {
            get {
                return ResourceManager.GetString("MenuOpenDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Playlist....
        /// </summary>
        public static string MenuOpenPlaylist {
            get {
                return ResourceManager.GetString("MenuOpenPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Order.
        /// </summary>
        public static string MenuOrder {
            get {
                return ResourceManager.GetString("MenuOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Map.
        /// </summary>
        public static string MenuPortMap {
            get {
                return ResourceManager.GetString("MenuPortMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Map Settings....
        /// </summary>
        public static string MenuPortMapSettings {
            get {
                return ResourceManager.GetString("MenuPortMapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        public static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string MenuRepeat {
            get {
                return ResourceManager.GetString("MenuRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord.
        /// </summary>
        public static string MonitorChord {
            get {
                return ResourceManager.GetString("MonitorChord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string MonitorKeys {
            get {
                return ResourceManager.GetString("MonitorKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string MonitorNotes {
            get {
                return ResourceManager.GetString("MonitorNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string MonitorPan {
            get {
                return ResourceManager.GetString("MonitorPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string MonitorPart {
            get {
                return ResourceManager.GetString("MonitorPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone.
        /// </summary>
        public static string MonitorTone {
            get {
                return ResourceManager.GetString("MonitorTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voices.
        /// </summary>
        public static string MonitorVoices {
            get {
                return ResourceManager.GetString("MonitorVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string MonitorVolume {
            get {
                return ResourceManager.GetString("MonitorVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string NewPlaylistName {
            get {
                return ResourceManager.GetString("NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map {0}.
        /// </summary>
        public static string NewPortMapName {
            get {
                return ResourceManager.GetString("NewPortMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument: {0}.
        /// </summary>
        public static string NoteBadArgument {
            get {
                return ResourceManager.GetString("NoteBadArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --config {0}: {1} The usual settings folder is used instead..
        /// </summary>
        public static string NoteBadConfig {
            get {
                return ResourceManager.GetString("NoteBadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load: {0} — {1}.
        /// </summary>
        public static string NoteCannotLoad {
            get {
                return ResourceManager.GetString("NoteCannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the TMIDI definition file: {0} — {1}.
        /// </summary>
        public static string NoteCannotLoadDef {
            get {
                return ResourceManager.GetString("NoteCannotLoadDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the target module definitions: {0} — {1}.
        /// </summary>
        public static string NoteCannotLoadDefine {
            get {
                return ResourceManager.GetString("NoteCannotLoadDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load playlist: {0} — {1}.
        /// </summary>
        public static string NoteCannotLoadPlaylist {
            get {
                return ResourceManager.GetString("NoteCannotLoadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the settings folder: {0}.
        /// </summary>
        public static string NoteCannotOpenConfigFolder {
            get {
                return ResourceManager.GetString("NoteCannotOpenConfigFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open output: {0}.
        /// </summary>
        public static string NoteCannotOpenOutput {
            get {
                return ResourceManager.GetString("NoteCannotOpenOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save playlist: {0} — {1}.
        /// </summary>
        public static string NoteCannotSavePlaylist {
            get {
                return ResourceManager.GetString("NoteCannotSavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the settings: {0} — {1}.
        /// </summary>
        public static string NoteCannotSaveSettings {
            get {
                return ResourceManager.GetString("NoteCannotSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the module initialization: {0}.
        /// </summary>
        public static string NoteCannotSendInit {
            get {
                return ResourceManager.GetString("NoteCannotSendInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open in the file manager: {0}.
        /// </summary>
        public static string NoteCannotShowFile {
            get {
                return ResourceManager.GetString("NoteCannotShowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write the sample target module definitions: {0} — {1}.
        /// </summary>
        public static string NoteCannotWriteDefineSample {
            get {
                return ResourceManager.GetString("NoteCannotWriteDefineSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while closing output: {0}.
        /// </summary>
        public static string NoteClosingOutput {
            get {
                return ResourceManager.GetString("NoteClosingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target module definitions read from {0} in place of the shipped ones.
        /// </summary>
        public static string NoteDefineOverride {
            get {
                return ResourceManager.GetString("NoteDefineOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target module definitions: {0}.
        /// </summary>
        public static string NoteDefineProblem {
            get {
                return ResourceManager.GetString("NoteDefineProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target module detected: {0}.
        /// </summary>
        public static string NoteDetected {
            get {
                return ResourceManager.GetString("NoteDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target module detected: {0}, played as {1}.
        /// </summary>
        public static string NoteDetectedPlaysAs {
            get {
                return ResourceManager.GetString("NoteDetectedPlaysAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection gave up: {0}.
        /// </summary>
        public static string NoteDetectFailed {
            get {
                return ResourceManager.GetString("NoteDetectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output stopped responding: {0}.
        /// </summary>
        public static string NoteDeviceLost {
            get {
                return ResourceManager.GetString("NoteDeviceLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulation: {0} ← {1}  {2}.
        /// </summary>
        public static string NoteEmulation {
            get {
                return ResourceManager.GetString("NoteEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Tone Fallback: {0} tone tables.
        /// </summary>
        public static string NoteFallbackTables {
            get {
                return ResourceManager.GetString("NoteFallbackTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped by a safety limit: {0}.
        /// </summary>
        public static string NoteFaulted {
            get {
                return ResourceManager.GetString("NoteFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initialization in the TMIDI definition file is too long and was cut short.
        /// </summary>
        public static string NoteInitCut {
            get {
                return ResourceManager.GetString("NoteInitCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization: {0} ({1}).
        /// </summary>
        public static string NoteInitialize {
            get {
                return ResourceManager.GetString("NoteInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song lengths measured: {0}.
        /// </summary>
        public static string NoteLengthsScanned {
            get {
                return ResourceManager.GetString("NoteLengthsScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target module definitions not found: {0}.
        /// </summary>
        public static string NoteNoDefine {
            get {
                return ResourceManager.GetString("NoteNoDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playable files found.
        /// </summary>
        public static string NoteNothingPlayable {
            get {
                return ResourceManager.GetString("NoteNothingPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output not found: {0}.
        /// </summary>
        public static string NoteOutputNotFound {
            get {
                return ResourceManager.GetString("NoteOutputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs: {0}.
        /// </summary>
        public static string NoteOutputs {
            get {
                return ResourceManager.GetString("NoteOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned every note off: the output may have lost messages it was sent: {0}.
        /// </summary>
        public static string NoteOutputSilenced {
            get {
                return ResourceManager.GetString("NoteOutputSilenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output changes take effect from the next song.
        /// </summary>
        public static string NoteOutputsNextSong {
            get {
                return ResourceManager.GetString("NoteOutputsNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated “{0}”.
        /// </summary>
        public static string NotePlaylistDuplicated {
            get {
                return ResourceManager.GetString("NotePlaylistDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported playlist: {0}.
        /// </summary>
        public static string NotePlaylistExported {
            get {
                return ResourceManager.GetString("NotePlaylistExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded playlist: {0}.
        /// </summary>
        public static string NotePlaylistLoaded {
            get {
                return ResourceManager.GetString("NotePlaylistLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved playlist: {0}.
        /// </summary>
        public static string NotePlaylistSaved {
            get {
                return ResourceManager.GetString("NotePlaylistSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port map: {0} ({1}).
        /// </summary>
        public static string NotePortMap {
            get {
                return ResourceManager.GetString("NotePortMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port map: {0} (takes effect from the next song).
        /// </summary>
        public static string NotePortMapNextSong {
            get {
                return ResourceManager.GetString("NotePortMapNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port map: {0} ({1} → {2}).
        /// </summary>
        public static string NotePortMapVia {
            get {
                return ResourceManager.GetString("NotePortMapVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring song lengths gave up: {0}.
        /// </summary>
        public static string NoteScanFailed {
            get {
                return ResourceManager.GetString("NoteScanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs added to “{1}”: {0}.
        /// </summary>
        public static string NoteSongsAdded {
            get {
                return ResourceManager.GetString("NoteSongsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs added to “{1}”: {0} (playback continues).
        /// </summary>
        public static string NoteSongsAddedPlaying {
            get {
                return ResourceManager.GetString("NoteSongsAddedPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs copied to “{1}”: {0}.
        /// </summary>
        public static string NoteSongsCopied {
            get {
                return ResourceManager.GetString("NoteSongsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs moved to “{1}”: {0}.
        /// </summary>
        public static string NoteSongsMoved {
            get {
                return ResourceManager.GetString("NoteSongsMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs removed from “{1}”: {0}.
        /// </summary>
        public static string NoteSongsRemoved {
            get {
                return ResourceManager.GetString("NoteSongsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs set back to auto-detect: {0}.
        /// </summary>
        public static string NoteSongsTargetCleared {
            get {
                return ResourceManager.GetString("NoteSongsTargetCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs set to target module {1}: {0}.
        /// </summary>
        public static string NoteSongsTargetSet {
            get {
                return ResourceManager.GetString("NoteSongsTargetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not switch songs: {0}.
        /// </summary>
        public static string NoteSwitchFailed {
            get {
                return ResourceManager.GetString("NoteSwitchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target module: {0}.
        /// </summary>
        public static string NoteTargetModule {
            get {
                return ResourceManager.GetString("NoteTargetModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        public static string NoteUnexpected {
            get {
                return ResourceManager.GetString("NoteUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output module not in the list, used as given: {0}.
        /// </summary>
        public static string NoteUnknownUseModule {
            get {
                return ResourceManager.GetString("NoteUnknownUseModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module: {0} (takes effect from the next song).
        /// </summary>
        public static string NoteUseModuleNextSong {
            get {
                return ResourceManager.GetString("NoteUseModuleNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By File Name.
        /// </summary>
        public static string OrderFileName {
            get {
                return ResourceManager.GetString("OrderFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string OrderRandom {
            get {
                return ResourceManager.GetString("OrderRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Order.
        /// </summary>
        public static string OrderRegistered {
            get {
                return ResourceManager.GetString("OrderRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Title.
        /// </summary>
        public static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its format version does not match: the file is version {0}, and this Glosa reads version {1}. Make it again from define.override.yaml.sample..
        /// </summary>
        public static string OverrideWrongVersion {
            get {
                return ResourceManager.GetString("OverrideWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string PaneDebug {
            get {
                return ResourceManager.GetString("PaneDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string PaneMonitor {
            get {
                return ResourceManager.GetString("PaneMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TMIDI Definition File.
        /// </summary>
        public static string PickDefinition {
            get {
                return ResourceManager.GetString("PickDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string PickFolder {
            get {
                return ResourceManager.GetString("PickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Playlist.
        /// </summary>
        public static string PickPlaylist {
            get {
                return ResourceManager.GetString("PickPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Songs.
        /// </summary>
        public static string PickSongs {
            get {
                return ResourceManager.GetString("PickSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string PlaylistAdd {
            get {
                return ResourceManager.GetString("PlaylistAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string PlaylistClose {
            get {
                return ResourceManager.GetString("PlaylistClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string PlaylistDuplicate {
            get {
                return ResourceManager.GetString("PlaylistDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as M3U....
        /// </summary>
        public static string PlaylistExportM3u {
            get {
                return ResourceManager.GetString("PlaylistExportM3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tab &quot;{0}&quot; has this file open. Save under another name..
        /// </summary>
        public static string PlaylistOpenInTab {
            get {
                return ResourceManager.GetString("PlaylistOpenInTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename....
        /// </summary>
        public static string PlaylistRename {
            get {
                return ResourceManager.GetString("PlaylistRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string PlaylistSave {
            get {
                return ResourceManager.GetString("PlaylistSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string PlaylistTabs {
            get {
                return ResourceManager.GetString("PlaylistTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open: {0}.
        /// </summary>
        public static string PortCannotOpen {
            get {
                return ResourceManager.GetString("PortCannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PortMapAdd {
            get {
                return ResourceManager.GetString("PortMapAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string PortMapAuto {
            get {
                return ResourceManager.GetString("PortMapAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string PortMapClearPort {
            get {
                return ResourceManager.GetString("PortMapClearPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear port {0}.
        /// </summary>
        public static string PortMapClearPortOf {
            get {
                return ResourceManager.GetString("PortMapClearPortOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This map is used when a song’s target module matches no other map. Target modules cannot be set for it..
        /// </summary>
        public static string PortMapDefaultTip {
            get {
                return ResourceManager.GetString("PortMapDefaultTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string PortMapGeneral {
            get {
                return ResourceManager.GetString("PortMapGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Maps.
        /// </summary>
        public static string PortMapList {
            get {
                return ResourceManager.GetString("PortMapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder. When more than one map claims the same target module, the higher one is used. The top map cannot be moved..
        /// </summary>
        public static string PortMapListTip {
            get {
                return ResourceManager.GetString("PortMapListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PortMapName {
            get {
                return ResourceManager.GetString("PortMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Ports.
        /// </summary>
        public static string PortMapPorts {
            get {
                return ResourceManager.GetString("PortMapPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Reset” marks the ports that are sent the module’s reset before each song while no TMIDI definition file is loaded. For one device on several ports, check only the first; for separate devices, check each of them. While a definition file is loaded, it decides, and this cannot be changed..
        /// </summary>
        public static string PortMapPortsTip {
            get {
                return ResourceManager.GetString("PortMapPortsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PortMapRemove {
            get {
                return ResourceManager.GetString("PortMapRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string PortMapReset {
            get {
                return ResourceManager.GetString("PortMapReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset port {0}.
        /// </summary>
        public static string PortMapResetOf {
            get {
                return ResourceManager.GetString("PortMapResetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Modules.
        /// </summary>
        public static string PortMapTargetModules {
            get {
                return ResourceManager.GetString("PortMapTargetModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the port map is “Auto”, songs for the target modules set here play through this map..
        /// </summary>
        public static string PortMapTargetModulesTip {
            get {
                return ResourceManager.GetString("PortMapTargetModulesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Map Settings.
        /// </summary>
        public static string PortMapTitle {
            get {
                return ResourceManager.GetString("PortMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string PortMapUseModule {
            get {
                return ResourceManager.GetString("PortMapUseModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (module).
        /// </summary>
        public static string PortMapUseModuleEmpty {
            get {
                return ResourceManager.GetString("PortMapUseModuleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the sound module connected to this map’s ports..
        /// </summary>
        public static string PortMapUseModuleTip {
            get {
                return ResourceManager.GetString("PortMapUseModuleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0}.
        /// </summary>
        public static string PortName {
            get {
                return ResourceManager.GetString("PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string PortOpen {
            get {
                return ResourceManager.GetString("PortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}): {2}.
        /// </summary>
        public static string PortOpenProblem {
            get {
                return ResourceManager.GetString("PortOpenProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unused).
        /// </summary>
        public static string PortUnused {
            get {
                return ResourceManager.GetString("PortUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PriorityNormal {
            get {
                return ResourceManager.GetString("PriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string ProblemDeviceNotFound {
            get {
                return ResourceManager.GetString("ProblemDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a MIDI output.
        /// </summary>
        public static string ProblemNotMidiOutput {
            get {
                return ResourceManager.GetString("ProblemNotMidiOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: dropped SysEx messages: {1}.
        /// </summary>
        public static string ProblemSysExDropped {
            get {
                return ResourceManager.GetString("ProblemSysExDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PromptCancel {
            get {
                return ResourceManager.GetString("PromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3125 bytes/s (MIDI cable).
        /// </summary>
        public static string RateMidiCable {
            get {
                return ResourceManager.GetString("RateMidiCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string RateUnlimited {
            get {
                return ResourceManager.GetString("RateUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Playlist.
        /// </summary>
        public static string RenamePlaylist {
            get {
                return ResourceManager.GetString("RenamePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string RenamePlaylistPrompt {
            get {
                return ResourceManager.GetString("RenamePlaylistPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat All.
        /// </summary>
        public static string RepeatAll {
            get {
                return ResourceManager.GetString("RepeatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string RepeatNone {
            get {
                return ResourceManager.GetString("RepeatNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Song.
        /// </summary>
        public static string RepeatSingle {
            get {
                return ResourceManager.GetString("RepeatSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat One.
        /// </summary>
        public static string RepeatSingleRepeat {
            get {
                return ResourceManager.GetString("RepeatSingleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Playlist.
        /// </summary>
        public static string SavePlaylist {
            get {
                return ResourceManager.GetString("SavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send All Sound Off on stop.
        /// </summary>
        public static string SettingsAllSoundOff {
            get {
                return ResourceManager.GetString("SettingsAllSoundOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes take effect immediately. Close the window when done..
        /// </summary>
        public static string SettingsAppliedAtOnce {
            get {
                return ResourceManager.GetString("SettingsAppliedAtOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playing songs dropped or opened from outside.
        /// </summary>
        public static string SettingsAutoDropPlay {
            get {
                return ResourceManager.GetString("SettingsAutoDropPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMIDI Definition File.
        /// </summary>
        public static string SettingsDefinition {
            get {
                return ResourceManager.GetString("SettingsDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect target modules with the TMIDI definition file.
        /// </summary>
        public static string SettingsDefKeywords {
            get {
                return ResourceManager.GetString("SettingsDefKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When off, songs are detected with the patterns in define.yaml. When on, they are detected with the [keyword] section of the TMIDI definition file. Changing this detects every song again..
        /// </summary>
        public static string SettingsDefKeywordsTip {
            get {
                return ResourceManager.GetString("SettingsDefKeywordsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As detected.
        /// </summary>
        public static string SettingsDetectedAsIs {
            get {
                return ResourceManager.GetString("SettingsDetectedAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Detection Names No Model.
        /// </summary>
        public static string SettingsDetectedDefaults {
            get {
                return ResourceManager.GetString("SettingsDetectedDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which target module a song detected as THRU, GS or XG is played as. &quot;As detected&quot; leaves it as it is. Songs whose target module was set by hand are not affected..
        /// </summary>
        public static string SettingsDetectedDefaultsTip {
            get {
                return ResourceManager.GetString("SettingsDetectedDefaultsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Module Detection.
        /// </summary>
        public static string SettingsDetection {
            get {
                return ResourceManager.GetString("SettingsDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model that wins.
        /// </summary>
        public static string SettingsDetectionPosition {
            get {
                return ResourceManager.GetString("SettingsDetectionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When more than one model is named, whether the one that comes first or the one that comes last is taken..
        /// </summary>
        public static string SettingsDetectionPositionTip {
            get {
                return ResourceManager.GetString("SettingsDetectionPositionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information to detect from (top first).
        /// </summary>
        public static string SettingsDetectionSources {
            get {
                return ResourceManager.GetString("SettingsDetectionSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the patterns in define.yaml search, and the song&apos;s data. Drag a line to move it. The song&apos;s data is used when the others name no model, so it is always last. It decides by the GS, XG and CM-64 initialization messages near the start of the song. The folder path is the part after your home folder. The attached text is the text file with the same name as the song. Changing this detects every song again..
        /// </summary>
        public static string SettingsDetectionSourcesTip {
            get {
                return ResourceManager.GetString("SettingsDetectionSourcesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string SettingsDisplay {
            get {
                return ResourceManager.GetString("SettingsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulation.
        /// </summary>
        public static string SettingsEmulation {
            get {
                return ResourceManager.GetString("SettingsEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Tone Fallback.
        /// </summary>
        public static string SettingsFallback {
            get {
                return ResourceManager.GetString("SettingsFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the module is a Sound Canvas from the SC-55mkII on (SC-55mkII, SC-33, SC-88, SC-88Pro, SC-8850), a variation tone or drum set it lacks plays on a close one, as on the SC-55..
        /// </summary>
        public static string SettingsFallbackTip {
            get {
                return ResourceManager.GetString("SettingsFallbackTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw with the hardware.
        /// </summary>
        public static string SettingsHardwareRendering {
            get {
                return ResourceManager.GetString("SettingsHardwareRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off, the processor draws the windows. This may use less memory, but puts more load on the processor..
        /// </summary>
        public static string SettingsHardwareRenderingTip {
            get {
                return ResourceManager.GetString("SettingsHardwareRenderingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endless loop repeats.
        /// </summary>
        public static string SettingsLoopCount {
            get {
                return ResourceManager.GetString("SettingsLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control with the media keys.
        /// </summary>
        public static string SettingsMediaKeys {
            get {
                return ResourceManager.GetString("SettingsMediaKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play, pause, stop and skip songs with the keyboard&apos;s media keys and the system&apos;s media controls..
        /// </summary>
        public static string SettingsMediaKeysTip {
            get {
                return ResourceManager.GetString("SettingsMediaKeysTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Output.
        /// </summary>
        public static string SettingsMidiOutput {
            get {
                return ResourceManager.GetString("SettingsMidiOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call midiOutReset on stop.
        /// </summary>
        public static string SettingsMidiOutReset {
            get {
                return ResourceManager.GetString("SettingsMidiOutReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the output module before each song.
        /// </summary>
        public static string SettingsModuleReset {
            get {
                return ResourceManager.GetString("SettingsModuleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without a TMIDI definition file, sends the reset that suits the output module to the port map&apos;s ports marked Reset..
        /// </summary>
        public static string SettingsModuleResetTip {
            get {
                return ResourceManager.GetString("SettingsModuleResetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process priority.
        /// </summary>
        public static string SettingsPriority {
            get {
                return ResourceManager.GetString("SettingsPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up song lengths and target modules in advance.
        /// </summary>
        public static string SettingsScanLength {
            get {
                return ResourceManager.GetString("SettingsScanLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads the songs in the list in advance, to show their lengths and target modules. When off, they are shown once a song has been played. Adding many songs takes longer..
        /// </summary>
        public static string SettingsScanLengthTip {
            get {
                return ResourceManager.GetString("SettingsScanLengthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequencer.
        /// </summary>
        public static string SettingsSequencer {
            get {
                return ResourceManager.GetString("SettingsSequencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes effect the next time Glosa starts..
        /// </summary>
        public static string SettingsTakesEffectAtStart {
            get {
                return ResourceManager.GetString("SettingsTakesEffectAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch tone maps to suit the target module.
        /// </summary>
        public static string SettingsToneMap {
            get {
                return ResourceManager.GetString("SettingsToneMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without a TMIDI definition file, when the output module is an SC-88 or later or an MU100 or later, plays a song for an earlier model on that model&apos;s tone map..
        /// </summary>
        public static string SettingsToneMapTip {
            get {
                return ResourceManager.GetString("SettingsToneMapTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is in format version {0}, newer than version {1}, which this Glosa reads.
        /// </summary>
        public static string SettingsTooNew {
            get {
                return ResourceManager.GetString("SettingsTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer rate limit.
        /// </summary>
        public static string SettingsTransferRate {
            get {
                return ResourceManager.GetString("SettingsTransferRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim extra spaces in titles.
        /// </summary>
        public static string SettingsTrimTitles {
            get {
                return ResourceManager.GetString("SettingsTrimTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string ShowFileName {
            get {
                return ResourceManager.GetString("ShowFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        public static string ShowPath {
            get {
                return ResourceManager.GetString("ShowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ShowTitle {
            get {
                return ResourceManager.GetString("ShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        public static string SongsCopyPath {
            get {
                return ResourceManager.GetString("SongsCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Playlist.
        /// </summary>
        public static string SongsCopyTo {
            get {
                return ResourceManager.GetString("SongsCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Playlist.
        /// </summary>
        public static string SongsMoveTo {
            get {
                return ResourceManager.GetString("SongsMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SongsRemove {
            get {
                return ResourceManager.GetString("SongsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string SongsShow {
            get {
                return ResourceManager.GetString("SongsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in File Manager.
        /// </summary>
        public static string SongsShowInFileManager {
            get {
                return ResourceManager.GetString("SongsShowInFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string SongsSort {
            get {
                return ResourceManager.GetString("SongsSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Module.
        /// </summary>
        public static string SongsTargetModule {
            get {
                return ResourceManager.GetString("SongsTargetModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By File Name.
        /// </summary>
        public static string SortFileName {
            get {
                return ResourceManager.GetString("SortFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Length (Shortest First).
        /// </summary>
        public static string SortLength {
            get {
                return ResourceManager.GetString("SortLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Length (Longest First).
        /// </summary>
        public static string SortLengthDescending {
            get {
                return ResourceManager.GetString("SortLengthDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Target Module.
        /// </summary>
        public static string SortModule {
            get {
                return ResourceManager.GetString("SortModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Path.
        /// </summary>
        public static string SortPath {
            get {
                return ResourceManager.GetString("SortPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Title.
        /// </summary>
        public static string SortTitle {
            get {
                return ResourceManager.GetString("SortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port map: {0}   Target: {1} → Module: {2}.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port map: {0}   Target: {1} → Module: {2}   {3}.
        /// </summary>
        public static string StatusWithEmulation {
            get {
                return ResourceManager.GetString("StatusWithEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (stopped).
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone map: {0}.
        /// </summary>
        public static string ToneMapInForce {
            get {
                return ResourceManager.GetString("ToneMapInForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TransportNext {
            get {
                return ResourceManager.GetString("TransportNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause / Resume.
        /// </summary>
        public static string TransportPause {
            get {
                return ResourceManager.GetString("TransportPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string TransportPlay {
            get {
                return ResourceManager.GetString("TransportPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string TransportPrevious {
            get {
                return ResourceManager.GetString("TransportPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string TransportSeek {
            get {
                return ResourceManager.GetString("TransportSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TransportStop {
            get {
                return ResourceManager.GetString("TransportStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong that Glosa was not prepared for. It carries on, but if it does not behave, restart it.
        ///
        ///{0}.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
    }
}
